config/routes.rb
Sicoca::Application.routes.draw do

  resources :sessions
  resources :placas
  resources :tipo_usuarios
  resources :pessoas
  resources :home

  resources :cabo_eleitorals , :belongs_to => :pessoa
  resources :carro_soms , :belongs_to => :pessoa
  resources :doacaos , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :tipo_usuarios
  resources :cavaletes, :belongs_to => :placas
  resources :placa_casas, :belongs_to => :pessoa
  resources :placa_casas, :belongs_to => :placas

  root :to => "sessions#new"
end

app/models/carro_som.rb
class CarroSom < ActiveRecord::Base
  belongs_to :pessoa
  
  accepts_nested_attributes_for :pessoa
  
  validates :placa_carro,  :presence => true
  validates :modelo_carro, :presence => true
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa ], 
            :conditions => ['pessoas.nome LIKE ? or placa_carro LIKE ? or modelo_carro LIKE ?',
                            "%#{search}%",       "%#{search}%",        "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/controllers/carro_soms_controller.rb
class CarroSomsController < ApplicationController
  
  before_filter :authenticate
  
  # GET /carro_soms
  # GET /carro_soms.xml
  def index
    @carro_soms = CarroSom.all
    @carro_soms = CarroSom.search(params[:search])
    @carro_soms = @carro_soms.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carro_soms }
    end
  end

  # GET /carro_soms/1
  # GET /carro_soms/1.xml
  def show
    @carro_som = CarroSom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @carro_som }
    end
  end

  # GET /carro_soms/new
  # GET /carro_soms/new.xml
  def new
    @carro_som = CarroSom.new
    @pessoa = Pessoa.new

    @pessoas = Pessoa.find(:all).map { |u| [u.nome + ' - ' + u.cpf + ';'] }.uniq
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @carro_som }
    end
  end

  # GET /carro_soms/1/edit
  def edit
    @carro_som = CarroSom.find(params[:id])
    @pessoas = Pessoa.find(:all).map { |u| [u.nome + ' - ' + u.cpf + ';'] }.uniq
  end

  # POST /carro_soms
  # POST /carro_soms.xml
  def create
    @carro_som = CarroSom.new(params[:carro_som])    
#    unless CarroSom.find(params[:pessoa.nome])
    @carro_som.pessoa = Pessoa.new(params[:pessoa])
 #   end

    respond_to do |format|
      if @carro_som.save
        format.html { redirect_to(@carro_som, :notice => ' - Carro de som cadastrado com sucesso.') }
        format.xml  { render :xml => @carro_som, :status => :created, :location => @carro_som }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @carro_som.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carro_soms/1
  # PUT /carro_soms/1.xml
  def update
    @carro_som = CarroSom.find(params[:id])
    @carro_som.pessoa.update_attributes(params[:pessoa])  

    respond_to do |format|
      if @carro_som.update_attributes(params[:carro_som])
        format.html { redirect_to(@carro_som, :notice => ' - Dados atualizados com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @carro_som.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carro_soms/1
  # DELETE /carro_soms/1.xml
  def destroy
    @carro_som = CarroSom.find(params[:id])
    @carro_som.destroy

    respond_to do |format|
      format.html { redirect_to(carro_soms_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  
  def authenticate
    if session[:logged]
      true
    else
      redirect_to :root
    end
  end
end

app/helpers/carro_soms_helper.rb
module CarroSomsHelper
end

app/views/carro_soms/edit.html.erb
<h1>Editar carro som</h1>

<script type="text/javascript"> 
	$(document).ready(function() {
			nomes = "<%= @pessoas %>";
			nomes = nomes.substring(0,nomes.length-1);
			nomesArray = nomes.split(";");
			
			$("#nomepessoa").autocomplete({
				source: nomesArray
			});
	});

	function digitacpf() {
		nomecpf = $("#nomepessoa").val().split(" - ");
		$("#nomepessoa").val(nomecpf[0]);
		$("#cpfpessoa").val(nomecpf[1]);
	}
</script>


<%= form_for(@carro_som) do |f| %>

  <% if @carro_som.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro_som.errors.count, "error") %> prohibited this carro_som from being saved:</h2>

      <ul>
      <% @carro_som.errors.full_messages.each do |msg| %>
        <li>
			<div class="iconeerro"></div>
			<b>Alerta: </b><%= msg %>
		</li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do carro</legend>
		<div class="field">
		  <%= f.label "Placa:" %>
		  <%= f.text_field :placa_carro %>
		</div>
		<div class="field">
		  <%= f.label "Modelo: " %>
		  <%= f.text_field :modelo_carro %>
		</div>
	</fieldset>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do dono do carro</legend>	
		<%= fields_for @carro_som.pessoa do |pessoa| %>
			<div class="field">
			  <%= pessoa.label "Nome: " %>
			  <%= pessoa.text_field :nome, :id => "nomepessoa", :onblur => "{digitacpf()}" %>
			</div>
			<div class="field">
			  <%= pessoa.label :pessoa, "CPF:" %>
			  <%= pessoa.text_field :cpf, :id => "cpfpessoa" %>
			</div>
		<% end %>	
		</fieldset>
  <div class="actions">
    <%= f.submit 'Salvar' %> |
 	<%= link_to 'Visualizar', @carro_som %> |
	<%= link_to 'Voltar', carro_soms_path %>
  </div>
<% end %>

app/views/carro_soms/index.html.erb
<h1>Carros de som<div class="busca">
	<% form_tag carro_soms_path, :class=> 'busca' , :method => 'get' do%>
		<%= text_field_tag :search, params[:search], :class => 'txtsalvar' %>
		<%= submit_tag "Buscar", :name => nil, :class => 'btsalvar' %>
	<% end %>		
</div></h1>

<table>
  <tr>
    <th>Placa carro</th>
    <th>Modelo carro</th>
    <th>Dono</th>
    <th class="botoes"></th>
    <th class="botoes"></th>
    <th class="botoes"></th>
  </tr>

<% @carro_soms.each do |carro_som| %>
  <tr>
    <td><%= carro_som.placa_carro %></td>
    <td><%= carro_som.modelo_carro %></td>
    <td><%= carro_som.pessoa.nome + " - " + carro_som.pessoa.cpf %></td>
    <td class="botoes"><%= link_to 'Visualizar', carro_som %></td>
    <td class="botoes"><%= link_to 'Editar', edit_carro_som_path(carro_som) %></td>
    <td class="botoes"><%= link_to 'Remover', carro_som, :confirm => 'Você tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div class="botoes_rodape" id="botoes_rodape">
	<%= link_to 'Cadastrar carro de som', new_carro_som_path %> |
	<%= link_to "Gerar relatório", carro_soms_path(@carro_som, :format => "pdf") %>
	<%= will_paginate @carro_som %>
</div>

app/views/carro_soms/new.html.erb
<h1>Novo carro de som</h1>

 

<script type="text/javascript"> 
	$(document).ready(function() {
			nomes = "<%= @pessoas %>";
			nomes = nomes.substring(0,nomes.length-1);
			nomesArray = nomes.split(";");
			
			$("#nomepessoa").autocomplete({
				source: nomesArray
			});
	});

	function digitacpf() {
		nomecpf = $("#nomepessoa").val().split(" - ");
		$("#nomepessoa").val(nomecpf[0]);
		$("#cpfpessoa").val(nomecpf[1]);
	}
</script>


<%= form_for :carro_som, :url => { :action => :create } do |f| %>

  <% if @carro_som.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro_som.errors.count, "error") %> prohibited this carro_som from being saved:</h2>

      <ul>
      <% @carro_som.errors.full_messages.each do |msg| %>
        <li>
			<div class="iconeerro"></div>
			<b>Alerta: </b><%= msg %>
		</li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do carro</legend>
		<div class="field">
		  <%= f.label "Placa:" %>
		  <%= f.text_field :placa_carro %>
		</div>
		<div class="field">
		  <%= f.label "Modelo: " %>
		  <%= f.text_field :modelo_carro %>
		</div>
	</fieldset>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do dono do carro</legend>	
		<%= fields_for :pessoa do |pessoa| %>
			<div class="field">
			  <%= pessoa.label "Nome: " %>
			  <%= pessoa.text_field :nome, :id => "nomepessoa", :onblur => "{digitacpf()}" %>
			</div>
			<div class="field">
			  <%= pessoa.label :pessoa, "CPF:" %>
			  <%= pessoa.text_field :cpf, :id => "cpfpessoa" %>
			</div>
		<% end %>	
		</fieldset>
  <div class="actions">
    <%= f.submit 'Salvar' %> | 
	<%= link_to 'Voltar', carro_soms_path %>
  </div>
<% end %>

app/views/carro_soms/show.html.erb
<h1>Carro de som <%= @carro_som.id %> <b id="notice"><%= notice %></b></h1>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do carro</legend>
		<p class="show">
			<b class="show">Placa carro:</b>
			<%= @carro_som.placa_carro %>
		</p>

		<p class="show">
			<b class="show">Modelo carro:</b>
			<%= @carro_som.modelo_carro %>
		</p>
	</fieldset>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do dono do carro</legend>
		<p class="show">
			<b class="show">Doador:</b>
			<%= @carro_som.pessoa.nome %>
		</p>
		<p class="show">
			<b class="show">CPF:</b>
			<%= @carro_som.pessoa.cpf %>
		</p>
	</fieldset>
	
<div class="botoes_rodape" id="botoes_rodape">
	<%= link_to 'Editar', edit_carro_som_path(@carro_som) %> |
	<%= link_to 'Voltar', carro_soms_path %>|
	<%= link_to "Gerar relatório", carro_som_path(@carro_som, :format => "pdf") %>
</div>