config/routes.rb
Sicoca::Application.routes.draw do

  resources :sessions
  resources :placas
  resources :tipo_usuarios
  resources :pessoas
  resources :home

  resources :cabo_eleitorals , :belongs_to => :pessoa
  resources :carro_soms , :belongs_to => :pessoa
  resources :doacaos , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :tipo_usuarios
  resources :cavaletes, :belongs_to => :placas
  resources :placa_casas, :belongs_to => :pessoa
  resources :placa_casas, :belongs_to => :placas

  root :to => "sessions#new"
end

app/models/placa_casa.rb
class PlacaCasa < ActiveRecord::Base
  belongs_to :placa
  belongs_to :pessoa
  
  accepts_nested_attributes_for :placa
  accepts_nested_attributes_for :pessoa
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa, :placa ], 
            :conditions => ['pessoas.nome LIKE ? or placas.endereco LIKE ? or placas.cidade LIKE ? or placas.cep LIKE ?',
                            "%#{search}%","%#{search}%","%#{search}%","%#{search}%"])
    else
      find(:all,
           :include => [:placa ],
           :order => 'placas.cep ASC')
    end
  end
  
  
end

app/controllers/placa_casas_controller.rb
class PlacaCasasController < ApplicationController
  
  before_filter :authenticate
  
  # GET /placa_casas
  # GET /placa_casas.xml
  def index
    @placa_casas = PlacaCasa.all
    @placa_casas = PlacaCasa.search(params[:search])
    @placa_casas = @placa_casas.paginate :page => params[:page], :order => 'created_at ASC', :per_page => 10

    @map = GMap.new("map_div")
    @map.control_init(:large_map => true,:map_type => true)
    @map.set_map_type_init(GMapType::G_NORMAL_MAP)
    @map.center_zoom_init(@placa_casas.first.placa.fetch_coordinates,11)

    @placa_casas.each do |placa_casa|
      @map.overlay_init(GMarker.new([placa_casa.placa.latitude,placa_casa.placa.longitude], :title => "Placa residencial", :info_window => "<b>Placa residencial</b><BR>" + placa_casa.placa.endereco))
      @marker = GMarker.new(placa_casa.placa.fetch_coordinates,:title => "Update", :info_window => "I have been placed through RJS")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @placa_casas }
    end
  end

  # GET /placa_casas/1
  # GET /placa_casas/1.xml
  def show
    @placa_casa = PlacaCasa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @placa_casa }
    end
  end

  # GET /placa_casas/new
  # GET /placa_casas/new.xml
  def new
    @placa_casa = PlacaCasa.new
    #   @placa      = Placa.new
    #  @pessoa     = Pessoa.new

    @pessoas = Pessoa.find(:all).map { |u| [u.nome + ' - ' + u.cpf + ';'] }.uniq

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @placa_casa }
    end
  end

  # GET /placa_casas/1/edit
  def edit
    @placa_casa = PlacaCasa.find(params[:id])
    @pessoas = Pessoa.find(:all).map { |u| [u.nome + ' - ' + u.cpf + ';'] }.uniq
  end

  # POST /placa_casas
  # POST /placa_casas.xml
  def create
    @placa_casa = PlacaCasa.new(params[:placa_casa])
    @placa_casa.pessoa = Pessoa.new(params[:pessoa])    
    @placa_casa.placa = Placa.new(params[:placa])

    respond_to do |format|
      if @placa_casa.save
        format.html { redirect_to(@placa_casa, :notice => ' - Placa cadastrada com sucesso.') }
        format.xml  { render :xml => @placa_casa, :status => :created, :location => @placa_casa }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @placa_casa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /placa_casas/1
  # PUT /placa_casas/1.xml
  def update
    @placa_casa = PlacaCasa.find(params[:id])
    @placa_casa.pessoa.update_attributes(params[:pessoa])  
    @placa_casa.placa.update_attributes(params[:placa])

    respond_to do |format|
      if @placa_casa.update_attributes(params[:placa_casa])
        format.html { redirect_to(@placa_casa, :notice => ' - Dados atualizados com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @placa_casa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /placa_casas/1
  # DELETE /placa_casas/1.xml
  def destroy
    @placa_casa = PlacaCasa.find(params[:id])
    @placa_casa.destroy

    respond_to do |format|
      format.html { redirect_to(placa_casas_url) }
      format.xml  { head :ok }
    end
  end

  def filepdf
    kit = PDFKit.new(html, :page_size => 'Letter')
    kit.stylesheets << '/path/to/css/file'
    pdf = kit.to_pdf
    file = kit.to_file('/path/to/save/pdf')
  end
  
  protected
  
  def authenticate
    if session[:logged]
      true
    else
      redirect_to :root
    end
  end
end

app/helpers/placa_casas_helper.rb
module PlacaCasasHelper
end

app/views/placa_casas/edit.html.erb
<h1>Editar placa residencial</h1>


<script type="text/javascript"> 
$(document).ready(function() {
	nomes = "<%= @pessoas %>";
	nomes = nomes.substring(0,nomes.length-1);
	nomesArray = nomes.split(";");

	$("#nomepessoa").autocomplete({
		source: nomesArray
	});
});

function digitacpf() {
	nomecpf = $("#nomepessoa").val().split(" - ");
	$("#nomepessoa").val(nomecpf[0]);
	$("#cpfpessoa").val(nomecpf[1]);
}
</script>


<%= form_for (@placa_casa) do |f| %>

<% if @placa_casa.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@placa_casa.errors.count, "error") %> prohibited this placa_casa from being saved:</h2>

	<ul>
		<% @placa_casa.errors.full_messages.each do |msg| %>
		<li>
			<div class="iconeerro"></div>
			<b>Alerta: </b>
			<div class="iconeerro"></div>
			<b>Alerta: </b><%= msg %>

		</li>
		<% end %>
	</ul>
</div>
<% end %>

<fieldset class="ui-widget-content ui-corner-all fieldset">
	<legend>Dados da placa</legend>
	<%= fields_for @placa_casa.placa do |placa| %>
	<div class="field">
		<%= placa.label "CEP: " %>
		<%= placa.text_field :cep %>
	</div>
	<div class="field">
		<%= placa.label "Endereço: " %>
		<%= placa.text_field :endereco %>
	</div>
	<div class="field">
		<%= placa.label "Cidade: " %>
		<%= placa.text_field :cidade %>
	</div>
	<div class="field">
		<%= placa.label "Tamanho" %>
		<%= placa.text_field :tamanho %>
	</div>
	<div class="field">
		<%= placa.label "Descrição: " %>
		<%= placa.text_field :descricao %>
	</div>
	<div class="field">
		<%= f.label "Autorizada:" %>
		<%= f.check_box :autoriza %>
	</div>
	<% end %>
</fieldset>
<fieldset class="ui-widget-content ui-corner-all fieldset">
	<legend>Dados de quem autorizou colocar a placa</legend>
	<%= fields_for @placa_casa.pessoa do |pessoa| %>
	<div class="field">
		<%= pessoa.label "Nome: " %>
		<%= pessoa.text_field :nome, :id => "nomepessoa", :onblur => "{digitacpf()}" %>
	</div>
	<div class="field">
		<%= pessoa.label :pessoa, "CPF:" %>
		<%= pessoa.text_field :cpf, :id => "cpfpessoa" %>
	</div>
	<% end %>
</fieldset>
<div class="actions">
	<%= f.submit 'Salvar' %> |
	<%= link_to 'Visualizar', @placa_casa %> | 
	<%= link_to 'Voltar', placa_casas_path %>
</div>
<% end %>

app/views/placa_casas/index.html.erb
<%= stylesheet_link_tag "simpletooltip" %>

<script type="text/javascript"> 
$(document).ready(function() {
	$("#imgautorizas").simpletooltip();
	$("#imgautorizan").simpletooltip();
});
</script>

<h1>Placas em residências<div class="busca">
	<% form_tag placa_casas_path, :class=> 'busca' , :method => 'get' do%>
	<%= text_field_tag :search, params[:search], :class => 'txtsalvar' %>
	<%= submit_tag "Buscar", :name => nil, :class => 'btsalvar' %>
	<% end %>		
</div></h1>

<%= raw(@map.to_html) %> <%= raw(@map.div(:width => 787, :height => 200)) %>

<table>
	<tr>
		<th id="tautorizada" width="10px"></th>
		<th>Cidade</th>
		<th>Endereço</th>
		<th>Utilizador</th>
		<th class="botoes"></th>
		<th class="botoes"></th>
		<th class="botoes"></th>
	</tr>

	<% @placa_casas.each do |placa_casa| %>
	<tr>
		<td id="autorizada" width="10px">
			<%= if placa_casa.autoriza == true
				image_tag("thumb-up.png", :title => "Placa autorizada", :id => "imgautorizas")
			else
				image_tag("thumb-down.png", :title => "Placa não autorizada", :id => "imgautorizan")
			end %>
		</td>
		<td><%= placa_casa.placa.cidade %></td>
		<td><%= placa_casa.placa.endereco %></td>
		<td><%= placa_casa.pessoa.nome %></td>
		<td class="botoes"><%= link_to 'Visualizar', placa_casa %></td>
		<td class="botoes"><%= link_to 'Editar', edit_placa_casa_path(placa_casa) %></td>
		<td class="botoes"><%= link_to 'Remover', placa_casa, :confirm => 'Você tem certeza?', :method => :delete %></td>
	</tr>
	<% end %>
</table>

<br />

<div class="botoes_rodape" id="botoes_rodape">
	<%= link_to 'Cadastrar placa', new_placa_casa_path %> |
	<%= link_to "Gerar relatório", placa_casas_path(@placa_casa, :format => "pdf") %>
	<%= will_paginate @placa_casa %>
</div>

app/views/placa_casas/new.html.erb
<h1>Nova placa residencial</h1>


<script type="text/javascript"> 
$(document).ready(function() {
	nomes = "<%= @pessoas %>";
	nomes = nomes.substring(0,nomes.length-1);
	nomesArray = nomes.split(";");

	$("#nomepessoa").autocomplete({
		source: nomesArray
	});
});

function digitacpf() {
	nomecpf = $("#nomepessoa").val().split(" - ");
	$("#nomepessoa").val(nomecpf[0]);
	$("#cpfpessoa").val(nomecpf[1]);
}
</script>


<%= form_for @placa_casa, :url => { :action => :create } do |f| %>

<% if @placa_casa.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@placa_casa.errors.count, "error") %> prohibited this placa_casa from being saved:</h2>

	<ul>
		<% @placa_casa.errors.full_messages.each do |msg| %>
		<li>
			<div class="iconeerro"></div>
			<b>Alerta: </b><%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<fieldset class="ui-widget-content ui-corner-all fieldset">
	<legend>Dados da placa</legend>
	<%= fields_for :placa do |placa| %>
	<div class="field">
		<%= placa.label "CEP: " %>
		<%= placa.text_field :cep %>
	</div>
	<div class="field">
		<%= placa.label "Endereço: " %>
		<%= placa.text_field :endereco %>
	</div>
	<div class="field">
		<%= placa.label "Cidade: " %>
		<%= placa.text_field :cidade %>
	</div>
	<div class="field">
		<%= placa.label "Tamanho" %>
		<%= placa.text_field :tamanho %>
	</div>
	<div class="field">
		<%= placa.label "Descrição: " %>
		<%= placa.text_field :descricao %>
	</div>
	<div class="field">
		<%= f.label "Autorizada:" %>
		<%= f.check_box :autoriza %>
	</div>
	<% end %>
</fieldset>
<fieldset class="ui-widget-content ui-corner-all fieldset">
	<legend>Dados de quem autorizou colocar a placa</legend>
	<%= fields_for :pessoa do |pessoa| %>
	<div class="field">
		<%= pessoa.label "Nome: " %>
		<%= pessoa.text_field :nome, :id => "nomepessoa", :onblur => "{digitacpf()}" %>
	</div>
	<div class="field">
		<%= pessoa.label :pessoa, "CPF:" %>
		<%= pessoa.text_field :cpf, :id => "cpfpessoa" %>
	</div>
	<% end %>
</fieldset>
<div class="actions">
	<%= f.submit 'Salvar' %> |
	<%= link_to 'Voltar', placa_casas_path %>
</div>
<% end %>

app/views/placa_casas/show.html.erb
<h1>Placa residencial <%= @placa_casa.id %> <b id="notice"><%= notice %></b></h1>

<fieldset class="ui-widget-content ui-corner-all fieldset">
	<legend>Dados da placa</legend>


	<p class="show">
		<b class="show">Cidade:</b>
		<%= @placa_casa.placa.cidade %>
	</p>
	<p class="show">
		<b class="show">Endereço:</b>
		<%= @placa_casa.placa.endereco %>
	</p>
	<p class="show">
		<b class="show">CEP:</b>
		<%= @placa_casa.placa.cep %>
	</p>
	<p class="show">
		<b class="show">Tamanho:</b>
		<%= @placa_casa.placa.tamanho %>
	</p>
	<p class="show">
		<b class="show">Descrição:</b>
		<%= @placa_casa.placa.descricao %>
	</p>
	<p class="show" id="autorizada">
		<b class="show">Autorizada:</b>
		<%= if @placa_casa.autoriza == true
			"Sim"
		else
			"Não"
		end %>
	</p>
</fieldset>

<fieldset class="ui-widget-content ui-corner-all fieldset">
	<legend>Dados de quem autorizou colocar a placa</legend>
	<p class="show">
		<b class="show">Nome:</b>
		<%= @placa_casa.pessoa.nome %>
	</p>
	<p class="show">
		<b class="show">CPF:</b>
		<%= @placa_casa.pessoa.cpf %>
	</p>
</fieldset>

<p id="assinatura">Assinatura: __________________________________________</p>

<div class="botoes_rodape" id="botoes_rodape">
	<%= link_to 'Editar', edit_placa_casa_path(@placa_casa) %> |
	<%= link_to 'Voltar', placa_casas_path %> | 
	<%= link_to "Gerar autorização", placa_casa_path(@placa_casa, :format => "pdf") %>
</div>