config/routes.rb
Sicoca::Application.routes.draw do

  resources :sessions
  resources :placas
  resources :tipo_usuarios
  resources :pessoas
  resources :home

  resources :cabo_eleitorals , :belongs_to => :pessoa
  resources :carro_soms , :belongs_to => :pessoa
  resources :doacaos , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :tipo_usuarios
  resources :cavaletes, :belongs_to => :placas
  resources :placa_casas, :belongs_to => :pessoa
  resources :placa_casas, :belongs_to => :placas

  root :to => "sessions#new"
end

app/models/cabo_eleitoral.rb
class CaboEleitoral < ActiveRecord::Base
  belongs_to :pessoa

  accepts_nested_attributes_for :pessoa
  
  validates :tipo_ajuda,  :presence => true
  validates :valor_ajuda, :presence => true, :numericality => true
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa ], 
            :conditions => ['pessoas.nome LIKE ? or tipo_ajuda LIKE ? or valor_ajuda LIKE ?',
                            "%#{search}%",       "%#{search}%",        "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/controllers/cabo_eleitorals_controller.rb
class CaboEleitoralsController < ApplicationController
  
  before_filter :authenticate
  
  # GET /cabo_eleitorals
  # GET /cabo_eleitorals.xml
  def index
    @cabo_eleitorals = CaboEleitoral.all
    @cabo_eleitorals = CaboEleitoral.search(params[:search])
    @cabo_eleitorals = @cabo_eleitorals.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cabo_eleitorals }
    end
  end

  # GET /cabo_eleitorals/1
  # GET /cabo_eleitorals/1.xml
  def show
    @cabo_eleitoral = CaboEleitoral.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cabo_eleitoral }
    end
  end

  # GET /cabo_eleitorals/new
  # GET /cabo_eleitorals/new.xml
  def new
    @cabo_eleitoral = CaboEleitoral.new
    @pessoa = Pessoa.new
    @pessoas = Pessoa.find(:all).map { |u| [u.nome + ' - ' + u.cpf + ';'] }.uniq
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cabo_eleitoral }
    end
  end

  # GET /cabo_eleitorals/1/edit
  def edit
    @cabo_eleitoral = CaboEleitoral.find(params[:id])
    @pessoas = Pessoa.find(:all).map { |u| [u.nome + ' - ' + u.cpf + ';'] }.uniq
  end

  # POST /cabo_eleitorals
  # POST /cabo_eleitorals.xml
  def create
    @cabo_eleitoral = CaboEleitoral.new(params[:cabo_eleitoral])
    @cabo_eleitoral.pessoa = Pessoa.new(params[:pessoa])    
    
    respond_to do |format|
      if @cabo_eleitoral.save
        format.html { redirect_to(@cabo_eleitoral, :notice => ' - Cabo eleitoral cadastrado com sucesso.') }
        format.xml  { render :xml => @cabo_eleitoral, :status => :created, :location => @cabo_eleitoral }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cabo_eleitoral.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cabo_eleitorals/1
  # PUT /cabo_eleitorals/1.xml
  def update
    @cabo_eleitoral = CaboEleitoral.find(params[:id])
    @cabo_eleitoral.pessoa.update_attributes(params[:pessoa])  

    respond_to do |format|
      if @cabo_eleitoral.update_attributes(params[:cabo_eleitoral])
        format.html { redirect_to(@cabo_eleitoral, :notice => ' - Dados atualizados com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cabo_eleitoral.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cabo_eleitorals/1
  # DELETE /cabo_eleitorals/1.xml
  def destroy
    @cabo_eleitoral = CaboEleitoral.find(params[:id])
    @cabo_eleitoral.destroy

    respond_to do |format|
      format.html { redirect_to(cabo_eleitorals_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  
  def authenticate
    if session[:logged]
      true
    else
      redirect_to :root
    end
  end
end

app/helpers/cabo_eleitorals_helper.rb
module CaboEleitoralsHelper
end

app/views/cabo_eleitorals/edit.html.erb
<h1>Editar cabo eleitoral</h1>

 

<script type="text/javascript"> 
	$(document).ready(function() {
			nomes = "<%= @pessoas %>";
			nomes = nomes.substring(0,nomes.length-1);
			nomesArray = nomes.split(";");
			
			$("#nomepessoa").autocomplete({
				source: nomesArray
			});
	});

	function digitacpf() {
		nomecpf = $("#nomepessoa").val().split(" - ");
		$("#nomepessoa").val(nomecpf[0]);
		$("#cpfpessoa").val(nomecpf[1]);
	}
</script>


<%= form_for(@cabo_eleitoral) do |f| %>

  <% if @cabo_eleitoral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabo_eleitoral.errors.count, "error") %> prohibited this cabo_eleitoral from being saved:</h2>

      <ul>
      <% @cabo_eleitoral.errors.full_messages.each do |msg| %>
        <li>
			<div class="iconeerro"></div>
			<b>Alerta: </b><%= msg %>
		</li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados da ajuda</legend>
		<div class="field">
		  <%= f.label "Tipo de ajuda: " %>
		  <%= f.text_field :tipo_ajuda %>
		</div>
		<div class="field">
		  <%= f.label "Valor da ajuda: " %>
		  <%= f.text_field :valor_ajuda %>
		</div>
	</fieldset>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do cabo eleitoral</legend>
		<%= fields_for @cabo_eleitoral.pessoa do |pessoa| %>
			<div class="field">
			  <%= pessoa.label "Nome: " %>
			  <%= pessoa.text_field :nome, :id => "nomepessoa", :onblur => "{digitacpf()}" %>
			</div>
			<div class="field">
			  <%= pessoa.label :pessoa, "CPF:" %>
			  <%= pessoa.text_field :cpf, :id => "cpfpessoa" %>
			</div>
		<% end %>
	</fieldset>
  <div class="actions">
    <%= f.submit 'Salvar' %> |
	<%= link_to 'Visualizar', @cabo_eleitoral %> |
	<%= link_to 'Voltar', cabo_eleitorals_path %>
  </div>
<% end %>

app/views/cabo_eleitorals/index.html.erb
<h1>Cabos eleitorais<div class="busca">
	<% form_tag cabo_eleitorals_path, :class=> 'busca' , :method => 'get' do%>
		<%= text_field_tag :search, params[:search], :class => 'txtsalvar' %>
		<%= submit_tag "Buscar", :name => nil, :class => 'btsalvar' %>
	<% end %>		
</div></h1>

<table>
  <tr>
    <th>Tipo de ajuda</th>
    <th>Valor de ajuda</th>
    <th>Cabo eleitoral</th>
    <th class="botoes"></th>
    <th class="botoes"></th>
    <th class="botoes"></th>
  </tr>

<% @cabo_eleitorals.each do |cabo_eleitoral| %>
  <tr>
    <td><%= cabo_eleitoral.tipo_ajuda %></td>
    <td><%= cabo_eleitoral.valor_ajuda %></td>
    <td><%= cabo_eleitoral.pessoa.nome %> - <%= cabo_eleitoral.pessoa.cpf %></td>
    <td class="botoes"><%= link_to 'Visualizar', cabo_eleitoral %></td>
    <td class="botoes"><%= link_to 'Editar', edit_cabo_eleitoral_path(cabo_eleitoral) %></td>
    <td class="botoes"><%= link_to 'Remover', cabo_eleitoral, :confirm => 'Você tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<div class="botoes_rodape" id="botoes_rodape">
	<%= link_to 'Cadastrar cabo eleitoral', new_cabo_eleitoral_path %> |
	<%= link_to "Gerar relatório", cabo_eleitorals_path(@cabo_eleitoral, :format => "pdf") %>
	<%= will_paginate @cabo_eleitorals %>
</div>

app/views/cabo_eleitorals/new.html.erb
<h1>Cadastrar novo cabo eleitoral</h1>

<script type="text/javascript"> 
	$(document).ready(function() {
			nomes = "<%= @pessoas %>";
			nomes = nomes.substring(0,nomes.length-1);
			nomesArray = nomes.split(";");
			
			$("#nomepessoa").autocomplete({
				source: nomesArray
			});
	});

	function digitacpf() {
		nomecpf = $("#nomepessoa").val().split(" - ");
		$("#nomepessoa").val(nomecpf[0]);
		$("#cpfpessoa").val(nomecpf[1]);
	}
</script>


<%= form_for :cabo_eleitoral, :url => { :action => :create } do |f| %>

  <% if @cabo_eleitoral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabo_eleitoral.errors.count, "error") %> prohibited this cabo_eleitoral from being saved:</h2>

      <ul>
      <% @cabo_eleitoral.errors.full_messages.each do |msg| %>
        <li>
			<div class="iconeerro"></div>
			<b>Alerta: </b><%= msg %>
		</li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados da ajuda</legend>
		<div class="field">
		  <%= f.label "Tipo de ajuda: " %>
		  <%= f.text_field :tipo_ajuda %>
		</div>
		<div class="field">
		  <%= f.label "Valor da ajuda: " %>
		  <%= f.text_field :valor_ajuda %>
		</div>
	</fieldset>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
	    <legend>Dados do cabo eleitoral</legend>
		<%= fields_for :pessoa do |pessoa| %>
			<div class="field">
			  <%= pessoa.label "Nome: " %>
			  <%= pessoa.text_field :nome, :id => "nomepessoa", :onblur => "{digitacpf()}" %>
			</div>
			<div class="field">
			  <%= pessoa.label :pessoa, "CPF:" %>
			  <%= pessoa.text_field :cpf, :id => "cpfpessoa" %>
			</div>
		<% end %>
	</fieldset>
  <div class="actions">
    <%= f.submit 'Salvar' %> | 
	<%= link_to 'Voltar', cabo_eleitorals_path %>
  </div>
<% end %>

app/views/cabo_eleitorals/show.html.erb
<h1>Cabo eleitoral <%= @cabo_eleitoral.id %> <b id="notice"><%= notice %></b></h1>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
		<legend>Dados da ajuda</legend>
		<p class="show">
			<b class="show">Tipo ajuda:</b>
			<%= @cabo_eleitoral.tipo_ajuda %>
		</p>
		<p class="show">
			<b class="show">Valor ajuda:</b>
			<%= @cabo_eleitoral.valor_ajuda %>
		</p>
	</fieldset>
	<fieldset class="ui-widget-content ui-corner-all fieldset">
		<legend>Dados do cabo eleitoral</legend>
		<p class="show">
			<b class="show">Nome:</b>
			<%= @cabo_eleitoral.pessoa.nome %>
		</p>
		<p class="show">
			<b class="show">CPF:</b>
			<%= @cabo_eleitoral.pessoa.cpf %>
		</p>
	</fieldset>
	
<div class="botoes_rodape" id="botoes_rodape">
	<%= link_to 'Editar', edit_cabo_eleitoral_path(@cabo_eleitoral) %> |
	<%= link_to 'Voltar', cabo_eleitorals_path %> |
	<%= link_to "Gerar relatório", cabo_eleitoral_path(@cabo_eleitoral, :format => "pdf") %>
</div>