config/routes.rb
Sicoca::Application.routes.draw do

  resources :sessions
  resources :placas
  resources :tipo_usuarios
  resources :pessoas
  resources :home

  resources :cabo_eleitorals , :belongs_to => :pessoa
  resources :carro_soms , :belongs_to => :pessoa
  resources :doacaos , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :pessoa
  resources :usuarios , :belongs_to => :tipo_usuarios
  resources :cavaletes, :belongs_to => :placas
  resources :placa_casas, :belongs_to => :pessoa
  resources :placa_casas, :belongs_to => :placas

  root :to => "sessions#new"
end

app/models/cabo_eleitoral.rb
class CaboEleitoral < ActiveRecord::Base
  belongs_to :pessoa

  accepts_nested_attributes_for :pessoa
  
  validates :tipo_ajuda,  :presence => true
  validates :valor_ajuda, :presence => true, :numericality => true
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa ], 
            :conditions => ['pessoas.nome LIKE ? or tipo_ajuda LIKE ? or valor_ajuda LIKE ?',
                            "%#{search}%",       "%#{search}%",        "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/models/carro_som.rb
class CarroSom < ActiveRecord::Base
  belongs_to :pessoa
  
  accepts_nested_attributes_for :pessoa
  
  validates :placa_carro,  :presence => true
  validates :modelo_carro, :presence => true
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa ], 
            :conditions => ['pessoas.nome LIKE ? or placa_carro LIKE ? or modelo_carro LIKE ?',
                            "%#{search}%",       "%#{search}%",        "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/models/cavalete.rb
class Cavalete < ActiveRecord::Base
  belongs_to :placa
  
  accepts_nested_attributes_for :placa
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :placa ], 
            :conditions => ['placas.endereco LIKE ? or placas.cidade  LIKE ? or placas.cep LIKE ?',
                            "%#{search}%","%#{search}%", "%#{search}%"])
    else
      find(:all,
           :include => [:placa ],
           :order => 'placas.cep ASC')
    end
  end
  
end

app/models/doacao.rb
class Doacao < ActiveRecord::Base
  belongs_to :pessoa
  
  accepts_nested_attributes_for :pessoa
    
  validates :valor_doaco,   :presence => true, :numericality => true
  validates :data_doacao,   :presence => true
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa ], 
            :conditions => ['pessoas.nome LIKE ? or valor_doaco LIKE ? or data_doacao LIKE ?',
                            "%#{search}%",       "%#{search}%",        "%#{search}%"])
    else
      find(:all)
    end
  end  
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  has_many :placa_casas,    :dependent => :destroy
  has_many :carro_soms,     :dependent => :destroy
  has_many :doacaos,        :dependent => :destroy
  has_one  :cabo_eleitoral, :dependent => :destroy
  has_one  :usuario,        :dependent => :destroy

  validates :nome,  :presence => true
  validates :cpf,   :presence => true
end

app/models/placa.rb
class Placa < ActiveRecord::Base
  has_many :placa_casas
  has_many :cavaletes
  
  after_validation :fetch_coordinates
  
  validates :endereco,  :presence => true
  validates :cidade,    :presence => true
  validates :tamanho,   :presence => true

  geocoded_by :endereco #joga latitude e longitude nos campos
  
#  def location
#    [:endereco, :cidade, "SC", "Brazil"].compact.join(', ')
#  end
end

app/models/placa_casa.rb
class PlacaCasa < ActiveRecord::Base
  belongs_to :placa
  belongs_to :pessoa
  
  accepts_nested_attributes_for :placa
  accepts_nested_attributes_for :pessoa
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa, :placa ], 
            :conditions => ['pessoas.nome LIKE ? or placas.endereco LIKE ? or placas.cidade LIKE ? or placas.cep LIKE ?',
                            "%#{search}%","%#{search}%","%#{search}%","%#{search}%"])
    else
      find(:all,
           :include => [:placa ],
           :order => 'placas.cep ASC')
    end
  end
  
  
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios
  
  validates :descricao, :presence => true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :tipo_usuario
  belongs_to :pessoa
  
  accepts_nested_attributes_for :tipo_usuario
  accepts_nested_attributes_for :pessoa
  
  validates :email, :presence => true
  validates :senha, :presence => true
  
  def self.search(search)
    if search
      find( :all, 
            :include => [ :pessoa ], 
            :conditions => ['pessoas.nome LIKE ? or email LIKE ?',
                            "%#{search}%",          "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate

  def index
  end

  protected

  def authenticate
    if session[:logged]
      true
    else
      redirect_to :root
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carro_soms_helper.rb
module CarroSomsHelper
end

app/helpers/cavaletes_helper.rb
module CavaletesHelper
end

app/helpers/doacaos_helper.rb
module DoacaosHelper
  def link_to_destroy(name, url, fallback_url)
    link_to_function name, "confirm_destroy(this, '#{url}')", :href => fallback_url
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/placa_casas_helper.rb
module PlacaCasasHelper
end

app/helpers/placas_helper.rb
module PlacasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SiCoCa - Sistema de Controle de Campanhas</title>
	<%= stylesheet_link_tag 'reset', 'sicoca', 'jquery-ui', 'imprimir', 'simpletooltip', :media => "all"  %>
	<%= javascript_include_tag "jquery","rails", "jquery-ui", "tooltip", 'googlemaps' %>
	<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key=ABQIAAAAsLuVwzoctv5Qdco_CapMIhQfFTG3ZIrwPnaM1-BOFI-jKPW2lhRdrfK3ES6knzNLjNL4je8U6Mmw5w&amp;hl=&amp;sensor=false" type="text/javascript"></script> 

	<%= csrf_meta_tag %>

	<script type="text/javascript"> 
	$(document).ready(function() {
		$( "button, input:submit, a" ).button();
		$( ":text, :password" ).addClass('text ui-widget-content ui-corner-all');
		$( ":text, :password" ).css({height: 20})
		$( ":select" ).addClass('text ui-widget-content ui-corner-all');
	});
	</script>
</head>

<body>
	<div class="main">
		<a class="toolbarimg naoimprimir" href="http://localhost:3000/home" id="imgtopo">
			<img class="header" src="../../../images/assis.png">
		</a>
		<div class="ui-widget-content ui-corner-all toolbar ui-widget-header barrabotoes" id="menutopo">
			<%= link_to "Manter bônus", doacaos_path, :class => "botaomenu" %>
			<%= link_to "Manter placas", placa_casas_path, :class => "botaomenu" %>
			<%= link_to "Manter cavaletes", cavaletes_path, :class => "botaomenu" %>
			<%= link_to "Manter cabos eleitorais", cabo_eleitorals_path, :class => "botaomenu" %>
			<%= link_to "Manter carros de som", carro_soms_path, :class => "botaomenu" %>
			<%= link_to "Manter usuários", usuarios_path, :class => "botaomenu" %>
		</div>
		<div class="ui-widget-content ui-corner-all content">
			<h1 class="relatorio">SiCoCa - Sistema para Controle de Campanhas</h1>
			<%= javascript_include_tag 'jquery','rails', 'jquery-ui', 'tooltip', 'googlemaps', 'ym4r-gm' %>
			<%= yield %>
			<% if session[:logged] %>
				<%= link_to "Sair", session_path(1), :method => :delete, :id => 'sair' %>
			<% end %>
		</div>
	</div>
</body>
</html>